import boto3

def create_glue_table(database_name, table_name, s3_location, columns):
    """
    Create a table in the AWS Glue Data Catalog.

    :param database_name: The name of the Glue database.
    :param table_name: The name of the new table.
    :param s3_location: The S3 location of the data (e.g., 's3://your-bucket/path/to/data/').
    :param columns: A list of column definitions as expected by Glue (generated by convert_struct_to_glue_data_types).
    """
    client = boto3.client('glue')

    try:
        response = client.create_table(
            DatabaseName=database_name,
            TableInput={
                'Name': table_name,
                'StorageDescriptor': {
                    'Columns': columns,
                    'Location': s3_location,
                    'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                    'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                    'SerdeInfo': {
                        'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                        'Parameters': {
                            'serialization.format': '1'
                        }
                    },
                },
                'TableType': 'EXTERNAL_TABLE',
                'Parameters': {
                    'classification': 'parquet',
                    'compressionType': 'none'
                }
            }
        )
        print(f"Table {table_name} created successfully in database {database_name}.")
    except Exception as e:
        print(f"An error occurred while creating the table: {str(e)}")

# Example usage
database_name = 'test_data'
table_name = 'test'
s3_location = 's3://cf-templates-rvk6ey9p6t0j-us-east-1/test/'

# Assuming glue_columns is generated from convert_struct_to_glue_data_types function
glue_columns = [
    {'Name': 'Invoice_ID', 'Type': 'string'},
    {'Name': 'Branch', 'Type': 'string'},
    {'Name': 'City', 'Type': 'string'},
    {'Name': 'Customer_type', 'Type': 'string'},
    {'Name': 'Gender', 'Type': 'string'},
    {'Name': 'Product_line', 'Type': 'string'},
    {'Name': 'Unit_price', 'Type': 'decimal(10,2)'},
    {'Name': 'Quantity', 'Type': 'int'},
    {'Name': 'Tax_5percent', 'Type': 'decimal(10,2)'},
    {'Name': 'Total', 'Type': 'decimal(10,2)'},
    {'Name': 'Time', 'Type': 'string'},  # Glue does not support time data type, hence representing as string
    {'Name': 'Payment', 'Type': 'string'},
    {'Name': 'cogs', 'Type': 'decimal(10,2)'},
    {'Name': 'gross_margin_percentage', 'Type': 'decimal(10,2)'},
    {'Name': 'gross_income', 'Type': 'decimal(10,2)'},
    {'Name': 'Rating', 'Type': 'decimal(10,2)'}
]

create_glue_table(database_name, table_name, s3_location, glue_columns)
